name: linuxserver-medusa
services:
  app:
    image: linuxserver/medusa:1.0.26@sha256:d042adae0e18e8b8b45f75d2ae3a685701b52e465f7cafa11939b5229b6cca43
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/medusa/config
        target: /config
      - type: bind
        source: /DATA/AppData/medusa/downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/medusa/tv
        target: /tv
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/abraxas678/CasaOS@gh-pages/apps/wisdomsky.linuxserver.linuxservermedusa/assets/icon.png
  title:
    en_US: Medusa (LinuxServer.io)
    zh_CN: Medusa（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxservermedusa
  port_map: '8081'
  version: 1.0.26
