name: linuxserver-rustdesk
services:
  app:
    image: linuxserver/rustdesk:1.4.9@sha256:58201de5f807e70ddc6d7a21255841570f5f780580f2fb9e3760941fb315cacd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rustdesk/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/abraxas678/CasaOS@gh-pages/apps/wisdomsky.linuxserver.linuxserverrustdesk/assets/icon.png
  title:
    en_US: Rustdesk (LinuxServer.io)
    zh_CN: Rustdesk（LinuxServer.io）
  id: wisdomsky.linuxserver.linuxserverrustdesk
  port_map: '3000'
  version: 1.4.9
